version: '3'

services:
  # Mongo
  mongodb:
    image: mongo
    container_name: portfolio-db
    ports:
      - "37017-37019:27017-27019"
    volumes:
      - /data/db

#  app:
#      build:
#        context: ./backend
#        dockerfile: Dockerfile
#      ports:
#        - 3000:3000
#      restart: unless-stopped
#      depends_on:
#        - mongodb

